Repository AY2324S1-CS2103T-F08-3/tp, pull requests merged in 2023-11, with the labels that each got.

#108 Implement persistent task storage
  src/main/java/seedu/address/model/animal/Animal.java
  src/main/java/seedu/address/model/animal/DateOfBirth.java
  src/main/java/seedu/address/model/animal/Task.java
  src/main/java/seedu/address/model/animal/TaskList.java
  src/main/java/seedu/address/storage/JsonAdaptedAnimal.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/AnimalCard.java
  src/main/java/seedu/address/ui/AnimalDetailPanel.java
  src/main/java/seedu/address/ui/AnimalListPanel.java
  src/main/resources/view/AnimalDetailPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonAnimalCatalogStorageTest/invalidAndValidAnimalsInCatalog.json
  src/test/data/JsonAnimalCatalogStorageTest/invalidAnimalsInCatalog.json
  src/test/data/JsonSerializableAnimalCatalogTest/duplicateAnimalsInCatalog.json
  src/test/data/JsonSerializableAnimalCatalogTest/typicalAnimalsCatalog.json
  src/test/java/seedu/address/model/animal/TaskListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAnimalTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/AnimalBuilder.java
  src/test/java/seedu/address/testutil/TypicalAnimals.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task, priority.High, severity.High

#119 Docs/add help animal command
  docs/SettingUp.md
  docs/UserGuide.md
  docs/index.md
Labels: priority.Medium, type.UG

#120 Make selectedAnimal reset after a command execution
  src/main/java/seedu/address/ui/AnimalListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity:Medium

#121 Make CommandBox Output Bigger
  src/main/resources/view/MainWindow.fxml
Labels: severity.Low

#191 Add Planned Enhancements for PE-D, and DetailedView in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Selected_Animal.png
Labels: type.DG, type.UG

#210 Docs/default UI
  docs/UserGuide.md
  docs/images/Ui_default.png
  docs/site.json
Labels: type.UG
