Repository AY2324S1-CS2103T-F08-3/tp, pull requests merged in 2023-10, with the labels that each got.

#28 Docs/dg nfrs user stories
  docs/DeveloperGuide.md
Labels: type.DG

#30 Update UserGuide.md
  docs/UserGuide.md
Labels: type.UG

#31 Update euchangxian's PPP 🎉 🎉 🎉
  docs/AboutUs.md
  docs/team/euchangxian.md
Labels: type.DG

#40 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.Medium, type.UG

#51 Refactor Address Book to store Animal details instead
  build.gradle
  codecov.yml
  src/main/java/seedu/address/commons/util/TimeUtil.java
  src/main/java/seedu/address/model/animal/AdmissionDate.java
  src/main/java/seedu/address/model/animal/Animal.java
  src/main/java/seedu/address/model/animal/Breed.java
  src/main/java/seedu/address/model/animal/DateOfBirth.java
  src/main/java/seedu/address/model/animal/Name.java
  src/main/java/seedu/address/model/animal/PetId.java
  src/main/java/seedu/address/model/animal/Sex.java
  src/main/java/seedu/address/model/animal/SexEnum.java
  src/main/java/seedu/address/model/animal/Species.java
  src/main/java/seedu/address/model/animal/healthStatus/Allergy.java
  src/main/java/seedu/address/model/animal/healthStatus/DietaryRestriction.java
  src/main/java/seedu/address/model/animal/healthStatus/HealthCategory.java
  src/main/java/seedu/address/model/animal/healthStatus/HealthStatus.java
  src/main/java/seedu/address/model/animal/healthStatus/Illness.java
  src/main/java/seedu/address/model/animal/healthStatus/SterilizationStatus.java
  src/main/java/seedu/address/model/animal/healthStatus/VaccinationStatus.java
  src/main/java/seedu/address/model/animal/notes/Note.java
  src/main/java/seedu/address/model/animal/notes/Notes.java
  src/main/java/seedu/address/model/animal/notes/PriorityEnum.java
  src/test/java/seedu/address/commons/util/TimeUtilTest.java
Labels: priority.High, severity.High

#52 Update user interface
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDetailPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailPanel.fxml
Labels: priority.Medium, severity.Low

#61 Update/animal catalog
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/AnimalCatalog.java
  src/main/java/seedu/address/model/AnimalModel.java
  src/main/java/seedu/address/model/AnimalModelManager.java
  src/main/java/seedu/address/model/animal/AdmissionDate.java
  src/main/java/seedu/address/model/animal/Animal.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/AnimalCard.java
  src/main/java/seedu/address/ui/AnimalDetailPanel.java
  src/main/java/seedu/address/ui/AnimalListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/AnimalDetailPanel.fxml
  src/main/resources/view/AnimalListCard.fxml
  src/main/resources/view/AnimalListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailPanel.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.High, severity.High

#66 Create list command
  src/main/java/seedu/address/logic/commands/ListAnimalCommand.java
  src/main/java/seedu/address/logic/parser/AnimalCatalogParser.java
  src/main/java/seedu/address/model/AnimalModel.java
  src/main/java/seedu/address/model/AnimalModelManager.java
Labels: priority.Medium, type.Story

#73 Add AnimalBuilder class
  src/test/java/seedu/address/testutil/AnimalBuilder.java
  src/test/java/seedu/address/testutil/TypicalAnimals.java
Labels: priority.High, severity:Medium

#79 Add UnitTests for AdmissionDate and DateofBirth
  build.gradle
  src/test/java/seedu/address/model/animal/AdmissionDateTest.java
  src/test/java/seedu/address/model/animal/DateOfBirthTest.java
Labels: priority.High

#80 Add unit tests for Breed and Species attributes
  src/test/java/seedu/address/model/animal/BreedTest.java
  src/test/java/seedu/address/model/animal/SpeciesTest.java
Labels: priority.High

#84 Update/dg
  docs/DeveloperGuide.md
Labels: type.DG

#87 Add Animal data persistence feature.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/AnimalLogicManager.java
  src/main/java/seedu/address/model/AnimalModel.java
  src/main/java/seedu/address/model/AnimalModelManager.java
  src/main/java/seedu/address/model/AnimalReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/AnimalUserPrefs.java
  src/main/java/seedu/address/model/animal/AdmissionDate.java
  src/main/java/seedu/address/model/animal/Animal.java
  src/main/java/seedu/address/model/animal/DateOfBirth.java
  src/main/java/seedu/address/model/animal/Sex.java
  src/main/java/seedu/address/storage/AnimalCatalogStorage.java
  src/main/java/seedu/address/storage/AnimalStorage.java
  src/main/java/seedu/address/storage/AnimalStorageManager.java
  src/main/java/seedu/address/storage/AnimalUserPrefsStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedAnimal.java
  src/main/java/seedu/address/storage/JsonAnimalCatalogStorage.java
  src/main/java/seedu/address/storage/JsonAnimalUserPrefsStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAnimalCatalog.java
  src/test/data/JsonAnimalCatalogStorageTest/invalidAndValidAnimalsInCatalog.json
  src/test/data/JsonAnimalCatalogStorageTest/invalidAnimalsInCatalog.json
  src/test/data/JsonAnimalCatalogStorageTest/notJsonFormatCatalog.json
  src/test/data/JsonAnimalUserPrefsStorageTest/EmptyUserPrefs.json
  src/test/data/JsonAnimalUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonAnimalUserPrefsStorageTest/NotJsonFormatUserPrefs.json
  src/test/data/JsonAnimalUserPrefsStorageTest/TypicalUserPref.json
  src/test/data/JsonSerializableAnimalCatalogTest/duplicateAnimalsInCatalog.json
  src/test/data/JsonSerializableAnimalCatalogTest/invalidAnimalsInCatalog.json
  src/test/data/JsonSerializableAnimalCatalogTest/typicalAnimalsCatalog.json
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/AddAnimalCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAnimalCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAnimalTest.java
  src/test/java/seedu/address/storage/JsonAnimalCatalogStorageTest.java
  src/test/java/seedu/address/storage/JsonAnimalUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAnimalCatalogTest.java
  src/test/java/seedu/address/testutil/TypicalAnimals.java
Labels: type.Epic, priority.High, severity.High

#93 Enable Assertions
  build.gradle
Labels: priority.High

#91 Update Storage in Developer Guide
  .gitignore
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
Labels: type.DG

#94 Refactor Commands
  build.gradle
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/AnimalLogic.java
  src/main/java/seedu/address/logic/AnimalMessages.java
  src/main/java/seedu/address/logic/commands/AddAnimalCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAnimalCommand.java
  src/main/java/seedu/address/logic/parser/AddAnimalCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliAnimalSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteAnimalCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/animal/DateOfBirth.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/AnimalMessagesTest.java
  src/test/java/seedu/address/logic/commands/AnimalCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteAnimalCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAnimalCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AnimalCommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/CliAnimalSyntaxTest.java
  src/test/java/seedu/address/logic/parser/DeleteAnimalCommandParserTest.java
  src/test/java/seedu/address/model/animal/DateOfBirthTest.java
Labels: type.Task, priority.High

#90 Update Model for DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.DG

#95 Add Task and TaskList Classes
  build.gradle
  src/main/java/seedu/address/model/animal/Animal.java
  src/main/java/seedu/address/model/animal/Task.java
  src/main/java/seedu/address/model/animal/TaskList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAnimal.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/AnimalCard.java
  src/main/java/seedu/address/ui/AnimalDetailPanel.java
  src/main/resources/view/AnimalDetailPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/animal/DateOfBirthTest.java
  src/test/java/seedu/address/model/animal/TaskListTest.java
  src/test/java/seedu/address/model/animal/TaskTest.java
  src/test/java/seedu/address/storage/JsonAnimalCatalogStorageTest.java
  src/test/java/seedu/address/storage/JsonAnimalUserPrefsStorageTest.java
Labels: type.Enhancement, priority.High
